-- CreateTable
CREATE TABLE `muser` (
    `nUserID` INTEGER NOT NULL AUTO_INCREMENT,
    `sName` VARCHAR(255) NOT NULL,
    `sEmail` VARCHAR(255) NOT NULL,
    `sMobile` VARCHAR(255) NULL,
    `sUserName` VARCHAR(255) NOT NULL,
    `sPassword` VARCHAR(255) NOT NULL,
    `sUserType` VARCHAR(255) NOT NULL,
    `sLevel` VARCHAR(255) NOT NULL,
    `sOtpAuth` VARCHAR(255) NOT NULL,
    `nCompanyID` INTEGER NOT NULL,

    PRIMARY KEY (`nUserID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `mcompany` (
    `nCompanyID` INTEGER NOT NULL AUTO_INCREMENT,
    `sName` VARCHAR(100) NOT NULL,
    `sAddr1` VARCHAR(100) NOT NULL,
    `sAddr2` VARCHAR(100) NULL,
    `sAddr3` VARCHAR(100) NULL,
    `sLogoPath` VARCHAR(100) NULL,
    `nCurrencyID` INTEGER UNSIGNED NULL,
    `sApplicableTaxName` VARCHAR(20) NULL,
    `nMarginPercentage` DOUBLE NULL,
    `nWastageMaterialPercentage` DOUBLE NULL,
    `nWastageEdgebrandingPercentage` DOUBLE NULL,
    `sPriceLevel1Name` VARCHAR(20) NULL,
    `sPriceLevel2Name` VARCHAR(20) NULL,
    `sPriceLevel3Name` VARCHAR(20) NULL,
    `nImageHeight` INTEGER UNSIGNED NULL DEFAULT 130,
    `sApplicableTaxNo` VARCHAR(100) NULL,
    `nNumberofUsers` INTEGER UNSIGNED NULL,
    `bActive` TINYINT UNSIGNED NULL,
    `sDefaultTerms1` VARCHAR(2000) NULL,
    `sDefaultTerms2` VARCHAR(2000) NULL,
    `sDefaultTerms3` VARCHAR(2000) NULL,
    `bTermsShow` TINYINT NULL,
    `sReportRequired` VARCHAR(50) NULL,
    `sCategorywiseReportColumns` VARCHAR(50) NULL,
    `sConsolidatedReportTerms` VARCHAR(10) NULL,
    `sCategoryReportTerms` VARCHAR(10) NULL,
    `sProcessReportTerms` VARCHAR(10) NULL,
    `sCuttingListReportColumns` VARCHAR(100) NOT NULL DEFAULT '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20',
    `sReportLabel1` VARCHAR(20) NULL,
    `sReportLabel2` VARCHAR(20) NULL,
    `sReportLabel3` VARCHAR(20) NULL,
    `sReportLabel4` VARCHAR(20) NULL,
    `bCompanyShow` TINYINT UNSIGNED NULL DEFAULT 0,
    `sCompanyKey` VARCHAR(100) NOT NULL DEFAULT '0',
    `sUploadType` VARCHAR(10) NOT NULL DEFAULT 'S3',
    `sConsolidatedReportColumns` VARCHAR(10) NULL,
    `bOTPRequired` TINYINT UNSIGNED NULL DEFAULT 0,
    `sSMSURL` VARCHAR(1000) NULL,
    `sNameLabel` VARCHAR(30) NULL,
    `sL1Label` VARCHAR(30) NULL,
    `sL2Label` VARCHAR(30) NULL,
    `sL3Label` VARCHAR(30) NULL,
    `sAreaLabel` VARCHAR(30) NULL,
    `sDescriptionLabel` VARCHAR(30) NULL,
    `sCoreMaterialLabel` VARCHAR(30) NULL,
    `sFinishLabel` VARCHAR(30) NULL,
    `sEdgebandingLabel` VARCHAR(30) NULL,
    `sFittingsLabel` VARCHAR(30) NULL,
    `sArticleCodeLabel` VARCHAR(30) NULL,
    `sVendorCodeLabel` VARCHAR(30) NULL,
    `sWeightLabel` VARCHAR(30) NULL,
    `sPerimeterLabel` VARCHAR(30) NULL,
    `sCutLengthLabel` VARCHAR(30) NULL,
    `sCutWidthLabel` VARCHAR(30) NULL,
    `sEL1Label` VARCHAR(30) NULL,
    `sEL2Label` VARCHAR(30) NULL,
    `sSL1Label` VARCHAR(30) NULL,
    `sSL2Label` VARCHAR(30) NULL,
    `sUserAttr1Label` VARCHAR(30) NULL,
    `sUserAttr2Label` VARCHAR(30) NULL,
    `sUserAttr3Label` VARCHAR(30) NULL,
    `sUserAttr4Label` VARCHAR(30) NULL,
    `sUserAttr5Label` VARCHAR(30) NULL,
    `sUserAttr6Label` VARCHAR(30) NULL,
    `sUserAttr7Label` VARCHAR(30) NULL,
    `sUserAttr8Label` VARCHAR(30) NULL,
    `sGroupNoLabel` VARCHAR(30) NULL,
    `sELLabel` VARCHAR(30) NULL,
    `sSLLabel` VARCHAR(30) NULL,
    `sItemCustomeField1Label` VARCHAR(30) NULL,
    `sItemCustomeField2Label` VARCHAR(30) NULL,
    `sItemCustomeField3Label` VARCHAR(30) NULL,
    `sItemCustomeField4Label` VARCHAR(30) NULL,
    `sSiteVisitChargesLabel` VARCHAR(30) NULL,
    `sManufacturingCostLabel` VARCHAR(30) NULL,
    `sInstallationAssemblyLabel` VARCHAR(30) NULL,
    `sAttachInDiscussionReq` VARCHAR(5) NOT NULL DEFAULT 'Yes',
    `sReplaceFuncReq` VARCHAR(5) NOT NULL DEFAULT 'Yes',
    `sSMSUtilityReq` VARCHAR(5) NOT NULL DEFAULT 'Yes',
    `sCustSMSModuleReq` VARCHAR(5) NOT NULL DEFAULT 'Yes',
    `nCompanyOneTimeFee` DOUBLE NULL,
    `dtCompAnnExpiryDate` VARCHAR(11) NULL,
    `sCompanyID` VARCHAR(50) NULL,
    `nPackageMasterID` INTEGER UNSIGNED NOT NULL,
    `nLogoPosition` TINYINT UNSIGNED NULL DEFAULT 0,
    `nAddressPosition` TINYINT UNSIGNED NULL DEFAULT 0,
    `sNestingReq` VARCHAR(5) NOT NULL DEFAULT 'No',
    `bNestingPriceCalMethod` TINYINT UNSIGNED NULL DEFAULT 0,
    `nSawKerfValue` DOUBLE NOT NULL DEFAULT 0,
    `nMinWasteSize` DOUBLE NOT NULL DEFAULT 0,
    `nLeftTrim` DOUBLE NOT NULL DEFAULT 0,
    `nRightTrim` DOUBLE NOT NULL DEFAULT 0,
    `nBottomTrim` DOUBLE NOT NULL DEFAULT 0,
    `nTopTrim` DOUBLE NOT NULL DEFAULT 0,
    `nCuttingComplexity` TINYINT UNSIGNED NULL DEFAULT 6,
    `bCuttingLayoutMin` TINYINT UNSIGNED NULL DEFAULT 0,
    `nMaxLayoutSize` INTEGER UNSIGNED NULL,
    `bMinmizePanelRotation` TINYINT NULL DEFAULT 0,
    `bConsolidatedReportShowProcess` TINYINT UNSIGNED NULL DEFAULT 1,
    `sNewItemFeatureReq` VARCHAR(5) NOT NULL DEFAULT 'No',
    `sUserDefinedChargesLabel2` VARCHAR(30) NULL,
    `sUserDefinedChargesLabel3` VARCHAR(30) NULL,
    `sUserDefinedChargesLabel4` VARCHAR(30) NULL,
    `sCutPartsLabel1` VARCHAR(50) NULL,
    `sCutPartsLabel2` VARCHAR(50) NULL,
    `sCutPartsLabel3` VARCHAR(50) NULL,
    `sCutPartsLabel4` VARCHAR(50) NULL,
    `sCutPartsLabel5` VARCHAR(50) NULL,
    `sCutPartsLabel6` VARCHAR(50) NULL,
    `sMRPReportCatIds` VARCHAR(1000) NULL,
    `sMRPReportProcessIds` VARCHAR(1000) NULL,
    `nNoofQuotperUser` INTEGER NULL DEFAULT 400,
    `nLeftTrim1D` DOUBLE NULL DEFAULT 0,
    `nRightTrim1D` DOUBLE NULL DEFAULT 0,
    `nSawKerfValue1D` DOUBLE NULL DEFAULT 0,
    `sGroupReportTerms` VARCHAR(10) NULL,
    `nGroupReportIncludeProcessCost` TINYINT UNSIGNED NULL,
    `nItemReportVisibletoCustomer` TINYINT UNSIGNED NULL DEFAULT 0,
    `sItemwiseReportColumns` VARCHAR(50) NULL,
    `sBoardPrice` VARCHAR(15) NOT NULL DEFAULT 'Level3Price',
    `bNoEdgebandReduction` TINYINT UNSIGNED NULL DEFAULT 1,
    `sCutPartsLabel7` VARCHAR(50) NULL,
    `sCutPartsLabel8` VARCHAR(50) NULL,
    `sCutPartsLabel9` VARCHAR(50) NULL,
    `sCutPartsLabel10` VARCHAR(50) NULL,
    `sCutPartsLabel11` VARCHAR(50) NULL,
    `sCutPartsLabel12` VARCHAR(50) NULL,
    `sCutPartsLabel13` VARCHAR(50) NULL,
    `sCutPartsLabel14` VARCHAR(50) NULL,
    `sCutPartsLabel15` VARCHAR(50) NULL,
    `nCutPartsLabel1CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel2CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel3CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel4CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel5CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel6CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel7CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel8CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel9CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel10CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel11CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel12CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel13CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel14CharLimit` VARCHAR(30) NULL,
    `nCutPartsLabel15CharLimit` VARCHAR(30) NULL,
    `nLabelCountnoofRows` INTEGER UNSIGNED NULL,
    `nLabelCountnoofColumns` INTEGER UNSIGNED NULL,
    `nMarginSettingTop` DOUBLE NULL,
    `nMarginSettingBottom` DOUBLE NULL,
    `nMarginSettingLeft` DOUBLE NULL,
    `nMarginSettingRight` DOUBLE NULL,
    `nLabelGapHorizontal` DOUBLE NULL,
    `nLabelGapVartical` DOUBLE NULL,
    `nLabelSizeWidth` DOUBLE NULL,
    `nLabelSizeHeight` DOUBLE NULL,
    `nnoofLinesPacking` INTEGER UNSIGNED NULL,
    `sStickerLabelCheckFields` VARCHAR(100) NULL,
    `sCalQtyLabel` VARCHAR(30) NULL,
    `nItemReportSizesVisible` TINYINT UNSIGNED NULL DEFAULT 1,
    `bCutDirection` TINYINT UNSIGNED NULL DEFAULT 0,
    `bRollMode` TINYINT UNSIGNED NULL DEFAULT 0,
    `sProjectNoLabel` VARCHAR(30) NULL,
    `sDefLanguage` TEXT NULL,
    `sRemarksAnneReportTerms` VARCHAR(10) NULL,
    `sRemarksAnneReportColumns` VARCHAR(20) NULL,
    `sGrossTotalLabel` VARCHAR(30) NULL,
    `sNetTotalLabel` VARCHAR(30) NULL,
    `bFixed` TINYINT NULL,
    `nCreatedID` INTEGER UNSIGNED NULL,
    `dtCreated` DATETIME(0) NULL,
    `nModifiedID` INTEGER UNSIGNED NULL,
    `dtModified` DATETIME(0) NULL,

    PRIMARY KEY (`nCompanyID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `muser` ADD CONSTRAINT `muser_nCompanyID_fkey` FOREIGN KEY (`nCompanyID`) REFERENCES `mcompany`(`nCompanyID`) ON DELETE RESTRICT ON UPDATE CASCADE;
